name: flutter_arc_text
description: Flutter widget that renders text along the arc with configurable radius.
version: 0.3.1
homepage: https://github.com/ookami-kb/flutter_arc_text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mews_pedantic: ^0.1.1
  flutter_test:
    sdk: flutter
